"""
AWS Dynamic Executor
====================
Executes boto3 API calls that were generated by the LLM and approved by the user.

Used in two places:
  1. Auto-execution: when action != alert_only and confidence is high
  2. Approval flow: user approves suggested_commands → this runs them

Safety:
  - ALLOWED_OPERATIONS allowlist: only these (service, method) pairs can run
  - BLOCKED_METHODS hard-stop: these can never run regardless of allowlist
  - Each call requires a human-readable 'description' for audit trail
  - Errors stop the chain — subsequent commands are not executed
"""

from __future__ import annotations

import logging
from typing import Any

import boto3
from botocore.exceptions import ClientError

logger = logging.getLogger(__name__)

# ── Allowlist ─────────────────────────────────────────────────────────────────
# Only these (service, method) combinations are permitted.
# Add new entries here when you need new capabilities.

ALLOWED_OPERATIONS: dict[str, list[str]] = {
    "iam": [
        "put_role_policy",
        "attach_role_policy",
        "get_role",
        "get_role_policy",
        "list_role_policies",
        "list_attached_role_policies",
    ],
    "lambda": [
        "update_function_configuration",  # increase_memory, increase_timeout
        "put_function_concurrency",  # set_concurrency
        "delete_function_concurrency",  # remove concurrency limit
        "update_alias",  # rollback_alias
        "get_function_configuration",
        "get_function",
        "list_aliases",
        "update_function_event_invoke_config",
        "put_function_event_invoke_config",
    ],
    "sqs": [
        "create_queue",
        "get_queue_url",
        "get_queue_attributes",
        "set_queue_attributes",
        "send_message",
        "receive_message",
        "delete_message",
        "purge_queue",  # clear DLQ after replay
    ],
    "dynamodb": [
        "create_table",
        "describe_table",
        "update_table",  # change capacity
        "put_item",
        "update_item",
        "get_item",
    ],
    "cloudwatch": [
        "put_metric_alarm",
        "describe_alarms",
        "disable_alarm_actions",
        "enable_alarm_actions",
    ],
    "logs": [
        "create_log_group",
        "put_retention_policy",
        "describe_log_groups",
    ],
    "ssm": [
        "put_parameter",
        "get_parameter",
        "get_parameters",
    ],
}

# ── Blocklist ─────────────────────────────────────────────────────────────────
# These method names can NEVER run, even if somehow in the allowlist.

BLOCKED_METHODS: frozenset[str] = frozenset(
    {
        "delete_function",
        "delete_table",
        "delete_queue",
        "delete_role",
        "delete_user",
        "delete_policy",
        "delete_role_policy",
        "detach_role_policy",
        "terminate_instances",
        "stop_instances",
        "delete_vpc",
        "delete_subnet",
        "delete_security_group",
        "delete_bucket",
        "delete_objects",
        "delete_object",
        "deregister_instance",
        "remove_permission",
    }
)


# ── Public API ────────────────────────────────────────────────────────────────


def validate_commands(commands: list[dict[str, Any]]) -> tuple[bool, str]:
    """
    Validate a list of commands against the allowlist.
    Called before storing in DynamoDB and again before execution.

    Returns (is_valid, reason).
    """
    if not commands:
        return False, "Empty command list"

    for i, cmd in enumerate(commands):
        service = str(cmd.get("service", "")).lower().strip()
        method = str(cmd.get("method", "")).lower().strip()

        if not service or not method:
            return False, f"Command #{i+1} is missing 'service' or 'method'"

        if not cmd.get("description"):
            return (
                False,
                f"Command #{i+1} is missing 'description' (required for audit)",
            )

        if method in BLOCKED_METHODS:
            return False, f"Command #{i+1}: '{service}.{method}' is permanently blocked"

        allowed = ALLOWED_OPERATIONS.get(service)
        if allowed is None:
            return False, f"Command #{i+1}: service '{service}' is not in the allowlist"

        if method not in allowed:
            return False, (
                f"Command #{i+1}: '{service}.{method}' is not in the allowlist. "
                f"Allowed methods for {service}: {allowed}"
            )

        # Reject placeholder values — LLM sometimes generates <role-name> or <account-id>
        # instead of real values. These will always cause AWS API errors.
        # However, for Lambda environment variables, we allow placeholders (like ${VAR_NAME} or <VAR_NAME>)
        # because we merge and filter them out during execution to keep the existing values.
        import copy
        params_to_check = copy.deepcopy(cmd.get("params", {}) or {})
        if (
            isinstance(params_to_check, dict)
            and "Environment" in params_to_check
            and isinstance(params_to_check["Environment"], dict)
            and "Variables" in params_to_check["Environment"]
        ):
            # Temporarily remove Environment.Variables for validation so placeholders are allowed there
            params_to_check["Environment"].pop("Variables")

        placeholders = _find_placeholders(params_to_check)
        if placeholders:
            return False, (
                f"Command #{i+1} ({service}.{method}) contains unfilled placeholders: "
                f"{placeholders}. Replace with actual AWS resource names/ARNs before executing."
            )

    return True, f"{len(commands)} command(s) validated OK"


def _find_placeholders(obj: Any, path: str = "") -> list[str]:
    """
    Recursively scan a params dict for LLM placeholder strings like <role-name> or ${role-name}.
    Returns a list of dotted paths to any placeholder values found.
    """
    import re
    # Match both <placeholder> and ${placeholder} formats
    _PLACEHOLDER = re.compile(r"<[^\u003e]+>|\$\{[^}]+\}")
    found: list[str] = []

    if isinstance(obj, str):
        if _PLACEHOLDER.search(obj):
            found.append(f"{path}=\"{obj}\"")
    elif isinstance(obj, dict):
        for k, v in obj.items():
            child_path = f"{path}.{k}" if path else k
            found.extend(_find_placeholders(v, child_path))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            found.extend(_find_placeholders(v, f"{path}[{i}]"))

    return found


def execute_commands(
    commands: list[dict[str, Any]],
    region: str = "us-east-1",
    dry_run: bool = False,
) -> list[dict[str, Any]]:
    """
    Execute a list of LLM-suggested boto3 calls in order.

    Each command dict:
        {
            "service":     "iam",
            "method":      "put_role_policy",
            "params":      {"RoleName": "...", "PolicyName": "...", "PolicyDocument": "..."},
            "description": "Add dynamodb:PutItem permission to sample-app-role",
            "risk":        "low | medium | high"
        }

    Stops on first failure — subsequent commands are not executed.

    Returns a list of result dicts, one per command attempted.
    """
    results: list[dict[str, Any]] = []

    for cmd in commands:
        result = _execute_one(cmd, region=region, dry_run=dry_run)
        results.append(result)

        if not result["success"] and not dry_run:
            logger.warning(
                f"[AWSExecutor] Chain stopped after failure: {result.get('error')}"
            )
            break

    return results


# ── Internal ──────────────────────────────────────────────────────────────────


def _execute_one(
    cmd: dict[str, Any],
    region: str,
    dry_run: bool,
) -> dict[str, Any]:
    service = str(cmd.get("service", "")).lower().strip()
    method = str(cmd.get("method", "")).lower().strip()
    params = cmd.get("params", {}) or {}
    description = cmd.get("description", "")
    risk = cmd.get("risk", "medium")

    base: dict[str, Any] = {
        "description": description,
        "service": service,
        "method": method,
        "risk": risk,
        "dry_run": dry_run,
    }

    # Re-validate before execution
    valid, reason = validate_commands([cmd])
    if not valid:
        return {**base, "success": False, "error": reason, "response": {}}

    if dry_run:
        logger.info(f"[AWSExecutor] DRY-RUN {service}.{method}({list(params.keys())})")
        return {
            **base,
            "success": True,
            "response": {"dry_run": True, "params": params},
            "error": None,
        }

    try:
        client = boto3.client(service, region_name=region)

        # Special case: lambda.update_function_configuration with Environment.Variables
        # must MERGE with existing env vars, not replace the entire set.
        # Without this, every update wipes all other env vars.
        if (
            service == "lambda"
            and method == "update_function_configuration"
            and "Environment" in params
            and "Variables" in params["Environment"]
        ):
            params = _merge_lambda_env_vars(client, params)

        fn = getattr(client, method)
        resp = fn(**params)
        resp.pop("ResponseMetadata", None)
        logger.info(f"[AWSExecutor] ✓ {service}.{method}")
        return {**base, "success": True, "response": resp, "error": None}

    except ClientError as exc:
        code = exc.response["Error"]["Code"]
        msg = exc.response["Error"]["Message"]
        logger.error(f"[AWSExecutor] ClientError {service}.{method}: {code}: {msg}")
        return {**base, "success": False, "error": f"{code}: {msg}", "response": {}}

    except Exception as exc:
        logger.error(f"[AWSExecutor] Error {service}.{method}: {exc}")
        return {**base, "success": False, "error": str(exc), "response": {}}


def _merge_lambda_env_vars(client: Any, params: dict[str, Any]) -> dict[str, Any]:
    """
    Merge new env vars with existing ones so we never wipe unrelated variables.

    Lambda's update_function_configuration replaces the ENTIRE Environment.Variables
    dict. This fetches the current vars first, merges (new values win), and returns
    updated params. If the fetch fails, returns params unchanged.

    Any placeholder value in the new variables (e.g. ${VAR_NAME} or <VAR_NAME>)
    is skipped so the existing live value is preserved.
    """
    function_name = params.get("FunctionName", "")
    new_vars: dict[str, str] = params["Environment"]["Variables"]

    try:
        current = client.get_function_configuration(FunctionName=function_name)
        existing_vars: dict[str, str] = (
            current.get("Environment", {}).get("Variables", {})
        )

        # Filter out placeholders from new_vars before merging.
        # We catch predefined tokens (__PRESERVE__), bracket formats, and typical placeholder words.
        clean_new_vars = {}
        for k, v in new_vars.items():
            if isinstance(v, str):
                v_strip = v.strip()
                v_lower = v_strip.lower()
                is_placeholder = (
                    v_lower == "__preserve__"
                    or (v_strip.startswith("${") and v_strip.endswith("}"))
                    or (v_strip.startswith("<") and v_strip.endswith(">"))
                    or "placeholder" in v_lower
                    or "preserve" in v_lower
                )
                if is_placeholder:
                    logger.info(f"[AWSExecutor] Ignoring placeholder env var {k}={v} — preserving existing value")
                    continue
            clean_new_vars[k] = v

        merged = {**existing_vars, **clean_new_vars}   # new_vars overwrite existing
        logger.info(
            f"[AWSExecutor] Merging env vars for {function_name}: "
            f"existing={list(existing_vars.keys())} updated={list(clean_new_vars.keys())}"
        )
        import copy
        merged_params = copy.deepcopy(params)
        merged_params["Environment"]["Variables"] = merged
        return merged_params
    except Exception as exc:
        logger.warning(
            f"[AWSExecutor] Could not fetch existing env vars for {function_name}, "
            f"proceeding with provided vars only: {exc}"
        )
        return params
