apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"telemetry.istio.io/v1alpha1","kind":"Telemetry","metadata":{"annotations":{},"name":"mesh-default","namespace":"istio-system"},"spec":{"metrics":[{"overrides":[{"disabled":false,"match":{"metric":"ALL_METRICS"}}],"providers":[{"name":"prometheus"}]}]}}
  creationTimestamp: "2026-02-28T17:34:51Z"
  generation: 1
  name: mesh-default
  namespace: istio-system
  resourceVersion: "5650"
  uid: fbcee7b1-32c6-4181-b7e0-0534174d30e1
spec:
  metrics:
  - overrides:
    - disabled: false
      match:
        metric: ALL_METRICS
    providers:
    - name: prometheus
