- job_name: istio-envoy
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_security_istio_io_tlsMode]
    action: keep
    regex: istio
  - source_labels: [__meta_kubernetes_pod_name]
    target_label: pod
  - source_labels: [__meta_kubernetes_pod_namespace]
    target_label: namespace
  - source_labels: [__meta_kubernetes_pod_ip]
    replacement: $1:15020
    target_label: __address__
  metrics_path: /stats/prometheus
  scheme: http
